# https://docs.neoforged.net/docs/gettingstarted/modfiles

modLoader = "lowcodefml"
loaderVersion = "[1,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

license = "AGPL-3.0"
issueTrackerURL = "https://github.com/BlueArchiveSchoolBanners/issues"

[[mods]]
modId = "bluearchiveschoolbanners"
version = "0.0.1"
displayName = "Blue Archive School Banners"
description = """A simple mod that adds Kivotos schools/clubs from Blue Archive as banner patterns"""
logoFile = "pack.png"
# updateJSONURL = ""
# credits = ""
authors = "general_gunner, EvanHsieh0415"
# displayURL = "https://github.com/"

[[dependencies.mod_id]]
modId = "minecraft"
type = "required" # required, optional, discouraged or incompatible. default is required
# reason = ""
versionRange = "[1.20.5,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
# ordering = "NONE" # NONE, AFTER, BEFORE. default is NONE
side = "BOTH" # BOTH, CLIENT, SERVER. default is BOTH